apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: c3-type-spot
spec:
  priorities:
  - machineType: c3-standard-8-lssd
    spot: true
  - machineType: c3d-standard-8-lssd
    spot: true
  - machineType: c3-standard-8-lssd
    spot: false
  nodePoolAutoCreation:
    enabled: true
  autoscalingPolicy:
    consolidationDelayMinutes: 1
  whenUnsatisfiable: DoNotScaleUp