apiVersion: v1
kind: Pod
metadata:
  name: cuda-pod
spec:
  nodeSelector:
    cloud.google.com/compute-class: prefer-l4-spot
  containers:
  - name: l4-container-1
    image: nvidia/cuda:11.0.3-runtime-ubuntu20.04
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 600; done;"]
    resources:
      limits:
        nvidia.com/gpu: 1
        cpu: "18"
        memory: "18Gi"
      requests:
        cpu: "18"
        memory: "18Gi"