apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: c3-lssd
spec:
  priorities:
  - machineType: c3-standard-8-lssd
    storage:
      bootDiskType: pd-balanced
      bootDiskSize: 250
      localSSDCount: 2
  - machineType: c3d-standard-8-lssd
    storage:
      bootDiskType: pd-balanced
      bootDiskSize: 250
      localSSDCount: 1
  autoscalingPolicy:
    consolidationDelayMinutes : 3
  activeMigration:
    optimizeRulePriority: true
  nodePoolAutoCreation:
    enabled: true
  whenUnsatisfiable: ScaleUpAnyway